// This file is generated by kconfig_compiler from scim_hangul.kcfg.
// All changes you do to this file will be lost.
#ifndef SCIMHANGULCONFIG_H
#define SCIMHANGULCONFIG_H

#include <kconfigskeleton.h>
#include <kdebug.h>

class ScimHangulConfig : public KConfigSkeleton
{
  public:

    static ScimHangulConfig *self();
    ~ScimHangulConfig();


    /**
      Get Whether to show the comment of candidates or not.
    */
    static
    bool _IMEngine_Hangul_ShowCandidateComment()
    {
      return self()->m_IMEngine_Hangul_ShowCandidateComment;
    }


    /**
      Get Whether to enable to change the input mode between hangul and ascii mode.
    */
    static
    bool _IMEngine_Hangul_UseAsciiMode()
    {
      return self()->m_IMEngine_Hangul_UseAsciiMode;
    }


    /**
      Get Whether not to commit until any non-hangul character is inputed.
    */
    static
    bool _IMEngine_Hangul_CommitByWord()
    {
      return self()->m_IMEngine_Hangul_CommitByWord;
    }


    /**
      Get Hangul keyboard layout
    */
    static
    QString _IMEngine_Hangul_KeyboardLayout()
    {
      return self()->m_IMEngine_Hangul_KeyboardLayout;
    }


    /**
      Get The key events to change input mode between hangul and ascii.
    */
    static
    QString _IMEngine_Hangul_HangulKey()
    {
      return self()->m_IMEngine_Hangul_HangulKey;
    }


    /**
      Get The key events to convert Hangul to Hanja character.
    */
    static
    QString _IMEngine_Hangul_HangulHanjaKey()
    {
      return self()->m_IMEngine_Hangul_HangulHanjaKey;
    }


    /**
      Get The key events to toggle Hanja mode.
    */
    static
    QString _IMEngine_Hangul_HanjaModeKey()
    {
      return self()->m_IMEngine_Hangul_HanjaModeKey;
    }

    static
    void writeConfig()
    {
      static_cast<KConfigSkeleton*>(self())->writeConfig();
    }
  protected:
    ScimHangulConfig();
    static ScimHangulConfig *mSelf;


    // SCIM
    bool m_IMEngine_Hangul_ShowCandidateComment;
    bool m_IMEngine_Hangul_UseAsciiMode;
    bool m_IMEngine_Hangul_CommitByWord;
    QString m_IMEngine_Hangul_KeyboardLayout;
    QString m_IMEngine_Hangul_HangulKey;
    QString m_IMEngine_Hangul_HangulHanjaKey;
    QString m_IMEngine_Hangul_HanjaModeKey;

  private:
};

#endif

